### ISSUE TITLE
lightning_channeld: Writing out status 65520: Broken pipe

### ISSUE THREAD

**Issue by robtex** [ElementsProject/lightning#1269]
got a lot of `lightning_channeld: Writing out status 65520: Broken pipe` so i ran in gdb

```
2018-03-25T09:29:17.068Z lightningd(25304): lightning_channeld-029441be72bfeef4bee881b44f52a601726e5be7c5d6cf9bb8f4f20123ea524ff7 chan #833: STATUS_FAIL_GOSSIP_IO: Can't read command: Connection reset by peer
2018-03-25T09:29:17.069Z lightningd(25304): 029441be72bfeef4bee881b44f52a601726e5be7c5d6cf9bb8f4f20123ea524ff7 chan #833: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (61952)
                                                                                                                                                          Program received signal SIGPIPE, Broken pipe.                                                                                                             0x00007ffff73102c0 in __write_nocancel () at ../sysdeps/unix/syscall-template.S:84                                                                        84      ../sysdeps/unix/syscall-template.S: No such file or directory.                                                                                    (gdb) bt
#0  0x00007ffff73102c0 in __write_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000043fdc4 in do_write_wire_header (fd=13, arg=0x875e30) at wire/wire_io.c:93
#2  0x000000000043fe55 in do_write_wire (fd=13, arg=0x875e30) at wire/wire_io.c:112
#3  0x00000000004640d4 in do_plan (conn=0x875db0, plan=0x875e10, idle_on_epipe=true) at ccan/ccan/io/io.c:374
#4  0x00000000004641d7 in io_ready (conn=0x875db0, pollflags=29) at ccan/ccan/io/io.c:403
#5  0x0000000000465ad0 in io_loop (timers=0x6ec120, expired=0x7fffffffde58) at ccan/ccan/io/poll.c:310
#6  0x0000000000414320 in main (argc=1, argv=0x7fffffffdf88) at lightningd/lightningd.c:407
```

**Comment by cdecker** [comment]
Seems this is just a peer losing its connection?

**Comment by robtex** [comment]
might be. i usually get about 5-20 of those before the main process terminates

**Comment by rustyrussell** [comment]
Looks like the peer reconnected while still connected: the message itself is harmless, but strange: this looks like two channelds, one exits because the gossipd fd closes, and one because the status fd closes.  I will add a test for this: I suspect we're accidentally killing both channelds instead of one.

**Comment by robtex** [comment]
not sure if this is related since there is no timestamp on the STDERR
https://github.com/ElementsProject/lightning/issues/1308

**Comment by cdecker** [comment]
The reconnection handling has been changed recently and this is unlikely to be reproducible now.
