### ISSUE TITLE
./configure check raises a non-critical core dump

### ISSUE THREAD

**Issue by m-schmoock** [ElementsProject/lightning#2351]
### Issue and Steps to Reproduce
When configuring the sandbox on `gcc (GCC) 8.2.1 20181127` a seamingly non-critical Segmentation fault is raised. The application compiles and runs normally.

```bash
lightning.git]$ ./configure --enable-developer
# ...
checking for working <ucontext.h... yes
checking for passing pointers via makecontext()... sh: line 1:  8792 Segmentation fault  (core dumped) ./configurator.out 2>&1
no
checking for libsodium with IETF chacha20 variants... yes
...
```

It seems to compile and test a code for a specific pointer behaviour.

### Caller
> configure
```bash
if valgrind -q --error-exitcode=7 --track-origins=yes --leak-check=full --show-reachable=yes --errors-for-leak-kinds=all $CONFIGURATOR --help >/dev/null 2>&1; then
```

### Code that causes it
> ccan/tools/configurator/configurator.c
```C
    { "HAVE_POINTER_SAFE_MAKECONTEXT", "passing pointers via makecontext()",    
      "DEFINES_EVERYTHING|EXECUTE|MAY_NOT_COMPILE",                                 
      "HAVE_UCONTEXT", NULL,                                                        
      "#include <stddef.h>\n"                                                       
      "#include <ucontext.h>\n"                                                     
      "static int worked = 0;\n"                                                    
      "static char stack[1024];\n"                                                  
      "static ucontext_t a, b;\n"                                                   
      "static void fn(void *p, void *q) {\n"                                        
      " void *cp = &worked;\n"                                                      
      " void *cq = (void *)(~((ptrdiff_t)cp));\n"                                   
      " if ((p == cp) && (q == cq))\n"                                              
      "     worked = 1;\n"                                                          
      " setcontext(&b);\n"                                                          
      "}\n"                                                                         
      "int main(void) {\n"                                                          
      " void *ap = &worked;\n"                                                      
      " void *aq = (void *)(~((ptrdiff_t)ap));\n"                                   
      " getcontext(&a);\n"                                                          
      " a.uc_stack.ss_sp = stack;\n"                                                
      " a.uc_stack.ss_size = sizeof(stack);\n"                                      
      " makecontext(&a, (void (*)(void))fn, 2, ap, aq);\n"                          
      " swapcontext(&b, &a);\n"                                                 
      " return worked ? 0 : 1;\n"                                               
      "}\n"                                                                     
    },
```

**Comment by m-schmoock** [comment]
This still persists, I have this on two different machines.

Details:
- `gcc (GCC) 8.2.1`

When compiling the following generated code by hand:
```C
#include <stddef.h>
#include <ucontext.h>

static int worked = 0;
static char stack[1024];
static ucontext_t a, b;

static void fn(void *p, void *q) {
	void *cp = &worked;
	void *cq = (void *)(~((ptrdiff_t)cp));
	if ((p == cp) && (q == cq))
		worked = 1;
	setcontext(&b);
}

int main(void) {
	void *ap = &worked;
	void *aq = (void *)(~((ptrdiff_t)ap));
	getcontext(&a);
	a.uc_stack.ss_sp = stack;
	a.uc_stack.ss_size = sizeof(stack);
	makecontext(&a, (void (*)(void))fn, 2, ap, aq);
	swapcontext(&b, &a);
	return worked ? 0 : 1;
}
```

We get the following `gdb` output:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fde4e1 in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2

(gdb) bt
#0  0x00007ffff7fde4e1 in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7fe2d17 in _dl_fixup () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7fe97ae in _dl_runtime_resolve_xsavec () from /lib64/ld-linux-x86-64.so.2
#3  0x00005555555551b9 in fn ()
#4  0x00007ffff7e3c860 in ?? () from /usr/lib/libc.so.6
#5  0x0000000000000000 in ?? ()
```

**Comment by rustyrussell** [comment]
AI cleanup of old issues.  If wrong, please open a new issue.


Triage decision summary:
Non-critical segmentation fault during ./configure check for makecontext pointer passing on GCC 8.2.1. Application compiles and runs normally despite the core dump. Issue is specific to configuration testing and unlikely to affect runtime functionality.
