### ISSUE TITLE
Make Millisatoshi JSON serializable

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3119]
### Issue and Steps to Reproduce

I'm writing some Python script that interact with c-lightning instances via pylightning. Many commands such as `listpeers` return a long JSON string, which is hard to make sense of in the terminal. I tried to pretty-print it using JSON package:
```
print(json.dumps(l1.listpeers()))
```
but got an error:
```
TypeError: Object of type 'Millisatoshi' is not JSON serializable
```
Would be nice to make Millisatoshi JSON-serializable to enable pretty-printing.

### `getinfo` output
```
{
   "id": "020bb1df60102c24c4b28612c23fb34356559a001924fa6997ba0ea5ee19bbed41",
   "alias": "PEEVEDWATCH",
   "color": "020bb1",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv6",
         "address": "<IP address>",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.7.2.1-291-g14b55d0",
   "blockheight": 378,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat"
}
```

**Comment by whitslack** [comment]
This deficiency also impacts the `lightning-pay` script that ships with C-Lightning.

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/lightning-pay", line 34, in <module>
    print("Bolt11 decoded:\n%s" % json.dumps(bolt11, indent=4))
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Millisatoshi' is not JSON serializable
```

**Comment by darosior** [comment]
You should not use `json.dumps` to pretty print but rather `pprint`?
```python
>>> import pprint
>>> pprint.pprint(l.listpeers())
{'peers': [{'channels': [{'channel_id': '25018ccc59e86a9d9cc6bbd45ea18e4e1e49fa464c78b7089123957306ef0e05',
                          'direction': 1,
                          'dust_limit_msat': 546000msat,
                          'dust_limit_satoshis': 546,
                          'funding_allocation_msat': {'02375c3dc568dc24b98f13c48602f4ec5cf3df2fc53a02181d8f8b687ded96043f': 0,
                                                      '038312b51675933faa9fbccc9cb13d85d0fd625880434521caa4ca26d79d100d44': 100000000},
                          'funding_msat': {'02375c3dc568dc24b98f13c48602f4ec5cf3df2fc53a02181d8f8b687ded96043f': '0msat',
                                           '038312b51675933faa9fbccc9cb13d85d0fd625880434521caa4ca26d79d100d44': '100000000msat'},
                          'funding_txid': '050eef067395239108b7784c46fa491e4e8ea15ed4bbc69c9d6ae859cc8c0125',
                          'htlc_minimum_msat': 0,
                          'htlcs': [],
                          'in_fulfilled_msat': 0msat,
                          'in_msatoshi_fulfilled': 0,
                          'in_msatoshi_offered': 0,
                          'in_offered_msat': 0msat,
                          'in_payments_fulfilled': 0,
                          'in_payments_offered': 0,
                          'max_accepted_htlcs': 483,
                          'max_htlc_value_in_flight_msat': 18446744073709551615,
                          'max_to_us_msat': 100000000msat,
                          'max_total_htlc_in_msat': 18446744073709551615msat,
                          'min_to_us_msat': 100000000msat,
                          'minimum_htlc_in_msat': 0msat,
                          'msatoshi_to_us': 100000000,
                          'msatoshi_to_us_max': 100000000,
                          'msatoshi_to_us_min': 100000000,
                          'msatoshi_total': 100000000,
                          'our_channel_reserve_satoshis': 1000,
                          'our_reserve_msat': 1000000msat,
                          'our_to_self_delay': 6,
                          'out_fulfilled_msat': 0msat,
                          'out_msatoshi_fulfilled': 0,
                          'out_msatoshi_offered': 0,
                          'out_offered_msat': 0msat,
                          'out_payments_fulfilled': 0,
                          'out_payments_offered': 0,
                          'owner': 'lightning_channeld',
                          'private': False,
                          'scratch_txid': '1595a562199b7545aa8f32ad990bb226fd2d8250f3bfddf7a4898bd2f800a9bf',
                          'short_channel_id': '127x1x0',
                          'spendable_msat': 98732000msat,
                          'spendable_msatoshi': 98732000,
                          'state': 'CHANNELD_NORMAL',
                          'status': ['CHANNELD_NORMAL:Funding transaction '
                                     'locked. Channel announced.'],
                          'their_channel_reserve_satoshis': 1000,
                          'their_reserve_msat': 1000000msat,
                          'their_to_self_delay': 6,
                          'to_us_msat': 100000000msat,
                          'total_msat': 100000000msat}],
            'connected': True,
            'globalfeatures': '',
            'id': '02375c3dc568dc24b98f13c48602f4ec5cf3df2fc53a02181d8f8b687ded96043f',
            'localfeatures': '28a2',
            'netaddr': ['127.0.0.1:11002']}]}
```
