### ISSUE TITLE
Pytest not working properly

### ISSUE THREAD

**Issue by Rda007** [ElementsProject/lightning#3651]
### Issue and Steps to Reproduce

**I am new to python and was trying to use pytest in a project.**

```python
def find_leap_years(given_year):
    if(given_year%100==0):
        if(given_year%4==0 or given_year%400==0):
            given_year=given_year
        else:
            given_year=given_year + (4-(given_year%4))
    else:
        given_year=given_year
    list_of_leap_years=[None]*15
    for index in range (0,15):
        list_of_leap_years[index]=given_year+4
        given_year=given_year+4
    return list_of_leap_years
list_of_leap_years=find_leap_years(2000)
print(list_of_leap_years)
```

above is the code I was trying to test using the below test module

```
import pytest
from src.solution import find_leap_years
def test_find_leap_years_1():
    result=find_leap_years(2002)
    assert result==[2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040, 2044, 2048, 2052, 2056, 2060]
```

but the following error was shown

```
_============================= test session starts =============================
platform win32 -- Python 3.8.0, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: C:\src\eclipse\eclipse-workspace\Assignment
[2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040, 2044, 2048, 2052, 2056, 2060]
collected 1 item

src\test_solution.py F
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\runner.py", line 100, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\runner.py", line 190, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\gours\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_runfiles\pydev_runfiles_pytest2.py", line 243, in pytest_runtest_logreport
INTERNALERROR>     exc = _get_error_contents_from_report(report)
INTERNALERROR>   File "C:\Users\gours\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_runfiles\pydev_runfiles_pytest2.py", line 147, in _get_error_contents_from_report
INTERNALERROR>     report.toterminal(tw)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\reports.py", line 65, in toterminal
INTERNALERROR>     longrepr.toterminal(out)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\_code\code.py", line 962, in toterminal
INTERNALERROR>     element[0].toterminal(tw)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\_code\code.py", line 992, in toterminal
INTERNALERROR>     entry.toterminal(tw)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\_code\code.py", line 1072, in toterminal
INTERNALERROR>     self._write_entry_lines(tw)
INTERNALERROR>   File "C:\Users\gours\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\_code\code.py", line 1062, in _write_entry_lines
INTERNALERROR>     tw._write_source(source_lines, indents)
INTERNALERROR> AttributeError: 'TerminalWriter' object has no attribute '_write_source'

============================== 1 failed in 0.11s ==============================_
```

How can I solve it?

**Comment by cdecker** [comment]
I'm afraid that this is not c-lightning related at all. In the trace there is no `pyln` or `pylightning` related file, and c-lightning does not support win32 in the first place.

May I suggest posting your issue to https://github.com/pytest-dev/pytest instead?
