### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#3779]
building the latest lightning with a 2.x python version returns this error:

```
if [ x"`git log doc/lightning-pay.7 | head -n1`" != x"`git log doc/lightning-pay.7.md | head -n1`" -o x"`git diff doc/lightning-pay.7.md`" != x"" ]; then mrkd doc/lightning-pay.7.md doc/lightning-pay.7; else touch doc/lightning-pay.7; fi
Traceback (most recent call last):
  File "/usr/local/bin/mrkd", line 6, in <module>
    from mrkd import main
  File "/usr/local/lib/python3.5/dist-packages/mrkd.py", line 40
    return f'{self.double_emphasis(text)}({section})'
                                                    ^
SyntaxError: invalid syntax
doc/Makefile:54: recipe for target 'doc/lightning-pay.7' failed
make: *** [doc/lightning-pay.7] Error 1
~/lightning$ python -V
Python 2.7.12
```

**Comment by cdecker** [comment]
We do not support `python2`, and it appears `mrkd` requires a newer `python3` as well: [f-string literal interpolation](https://www.python.org/dev/peps/pep-0498/) was added in python 3.6
