### ISSUE TITLE
Paying an invoice to Phoenix hangs forever

### ISSUE THREAD

**Issue by fiatjaf** [ElementsProject/lightning#4241]
### Issue and Steps to Reproduce
```
lightning-cli pay lnbc3m1p0udthdpp53cka254vc9fletymzrlt7kmlrfuyjnt4jmvsm56xjly4wqc0xmzqdq5ve6kuepqwp5x7etwd9uqxqrrss9qtzqqqqqq9qsqsp5ul3c0aqpa0x5ymzt97kkjxwfc6esyypc5xajukjatrm95grg3zjqrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll6nepahr0d4dqqqqqlgqqqqqeqqjqvzmme8k2uxag8zmssgyuppf8m0rvsl2n8t2t9fwdhhv0e6ff50u3t0nykzegfgtwm32m43096uw9yrql966rd4mw5gngx926znwlpeqpu4anm8
```

Hangs forever.

### `getinfo` output

```
{
   "id": "02c16cca44562b590dd279c942200bdccfd4f990c3a69fad620c10ef2f8228eaff",
   "alias": "@lntxbot",
   "color": "296683",
   "num_peers": 22,
   "num_pending_channels": 1,
   "num_active_channels": 21,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "5.2.67.89",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 3597
      }
   ],
   "version": "v0.9.2-28-g68c6ae6-modded",
   "blockheight": 659550,
   "network": "bitcoin",
   "msatoshi_fees_collected": 31840510,
   "fees_collected_msat": "31840510msat",
   "lightning-dir": "/home/fiatjaf/.lightning/bitcoin"
}
```

**Comment by ZmnSCPxj** [comment]
Yes, it can take a long time for payment to resolve.  Slow/unreliable forwarding nodes can lock up your payment up to the maximum HTLC timeout, which us measured in blocks, and using MPP means we tend to spread out to even more forwarding nodes, making it more likely we hit a slow/unreliable forwarding node.

**Comment by fiatjaf** [comment]
Sorry, I was drunk when I created this so it was silly.

The problem is that it hangs, but no entry for it is found on `listpays`. Shouldn't it be "pending" there while tries are being made?

And if I do `lightning-cli listpays -k payment_hash=<its-hash>` then `listpays` hangs forever.

Using `log-level=debug` seemed to show many attempts being made, but I'm not sure exactly since it is way too much output and not necessarily from that same `pay` attempt.

This has happened many times, but I cannot reproduce it reliably.

**Comment by ZmnSCPxj** [comment]
I think we have a number of inefficiencies over in the pay plugin.  Let us pester @cdecker about it.

**Comment by cdecker** [comment]
`lidtpays` should definitely not hang, unless the entire `pay` plugin is hanging (it just groups the result of `listsendpays` annotating it with additional information).

Can you share the logs around the time this happened? And if it happens again we could attach with `gdb` and get a backtrack:

```bash
gdb attach $(pgrep pay)

> bt
```
The `bt` command will print the current call stack, and you can share it here.

**Comment by fiatjaf** [comment]
```
~$ sudo gdb attach $(pgrep pay)
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: No such file or directory.
Attaching to process 193558
Reading symbols from target:/home/fiatjaf/lightning/plugins/pay...
Reading symbols from target:/lib/x86_64-linux-gnu/libm.so.6...
Reading symbols from target:/usr/lib/debug//lib/x86_64-linux-gnu/libm-2.31.so...
Reading symbols from target:/lib/x86_64-linux-gnu/libgcc_s.so.1...
(No debugging symbols found in target:/lib/x86_64-linux-gnu/libgcc_s.so.1)
Reading symbols from target:/lib/x86_64-linux-gnu/libc.so.6...
Reading symbols from target:/usr/lib/debug//lib/x86_64-linux-gnu/libc-2.31.so...
Reading symbols from target:/lib64/ld-linux-x86-64.so.2...
(No debugging symbols found in target:/lib64/ld-linux-x86-64.so.2)
0x00007f24d05d6ac7 in __GI___poll (fds=0x564c8d872458, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
29      ../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) bt
#0  0x00007f24d05d6ac7 in __GI___poll (fds=0x564c8d872458, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x0000564c8d0aeac6 in daemon_poll (fds=0x564c8d872458, nfds=3, timeout=-1) at common/daemon.c:94
#2  0x0000564c8d0c8943 in io_loop (timers=0x564c8d870460, expired=0x7ffe24630828) at ccan/ccan/io/poll.c:412
#3  0x0000564c8d095332 in plugin_main (argv=0x7ffe24630a78, init=0x564c8d0903ef <init>,
    restartability=PLUGIN_RESTARTABLE, init_rpc=true, features=0x0, commands=0x564c8d192740 <commands>, num_commands=4,
    notif_subs=0x0, num_notif_subs=0, hook_subs=0x0, num_hook_subs=0) at plugins/libplugin.c:1403
#4  0x0000564c8d090d98 in main (argc=1, argv=0x7ffe24630a78) at plugins/pay.c:2101
```

**Comment by fiatjaf** [comment]
I think I'll close this, as I identified some unrelated issues that may have been causing it and haven't seen it happen again anyway.

**Comment by cdecker** [comment]
Thanks for the update @fiatjaf, feel free to reopen if it happens again ^^
