### ISSUE TITLE
ValueError: Attempted to create a FileBackend, but file already exists.

### ISSUE THREAD

**Issue by freddiemacd** [ElementsProject/lightning#4459]
### Issue and Steps to Reproduce
I am following the instructions "backup Plugin And Remote NFS Mount" but I get this error.

```
pi@raspberrypi:~/.lightning/bitcoin $ /home/pi/plugins/backup/backup-cli init --lightning-dir ${LIGHTNINGDIR} file:///media/pi/20FE-24E2/
Traceback (most recent call last):
  File "/home/pi/plugins/backup/backup-cli", line 100, in <module>
    cli()
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/plugins/backup/backup-cli", line 27, in init
    backend = get_backend(destination, create=True)
  File "/home/pi/plugins/backup/backends.py", line 27, in get_backend
    backend = backend_cl(destination, create=create)
  File "/home/pi/plugins/backup/filebackend.py", line 19, in __init__
    raise ValueError("Attempted to create a FileBackend, but file already exists.")
ValueError: Attempted to create a FileBackend, but file already exists.
pi@raspberrypi:~/.lightning $ echo ${LIGHTNINGDIR}
/home/pi/.lightning/bitcoin/
```

### `get info` output

```
pi@raspberrypi:~/.lightning $ lightning-cli --lightning-dir=$HOME/.lightning getinfo
{
   "id": "xxx",
   "alias": "xxx",
   "color": "000000",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv2",
         "address": "xxx.onion",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "xxx.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9737
      }
   ],
   "version": "v0.9.3",
   "blockheight": 676752,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/pi/.lightning/bitcoin",
   "warning_lightningd_sync": "Still loading latest blocks from bitcoind."
```

**Comment by vincenzopalazzo** [comment]
I think that the error is the following line

>raise ValueError("Attempted to create a FileBackend, but file already exists.")

Maybe to avoid this problem you can move the existing file in another directory?.

But maybe the plugin needs to take in consideration this case.

P.S: I think the better location for this issue is the [lightnind/plugins](https://github.com/lightningd/plugins)

**Comment by freddiemacd** [comment]
I think you are right about where to ask about this issue, so I have posted it to lightningd/plugins.
