### ISSUE TITLE
Memory leak test failure in my local environment

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#470]
Not running inside docker, (running 0.7.0 bitcoinlib, not on #469)  I'm getting this test failure:

```bash
$ NO_VALGRIND=1 ARCH=64 make check
```

```

[..]

lightningd/test/run-find_my_path
make pytest
make[1]: Entering directory '/home/jb55/dev/github/ElementsProject/lightning'
PYTHONPATH+=:contrib/pylightning DEVELOPER=1 python3 tests/test_lightningd.py -f
Testing results are in /run/user/1000/lightning-iqbap4tv
test_addfunds_from_block (__main__.LightningDTests)
Send funds to the daemon without telling it explicitly ... ERROR

======================================================================
ERROR: test_addfunds_from_block (__main__.LightningDTests)
Send funds to the daemon without telling it explicitly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_lightningd.py", line 208, in tearDown
    ok = self.node_factory.killall([not n.may_fail for n in self.node_factory.nodes])
  File "tests/test_lightningd.py", line 158, in killall
    .format(self.nodes[i].daemon.lightning_dir, leaks))
Exception: Node /run/user/1000/lightning-iqbap4tv/test_addfunds_from_block/lightning-1/ has memory leaks:
```

```json
[
  {
    "value": "0x1bd2280",
    "label": "lightningd/log.c:103:struct log_book",
    "parents": []
  },
  {
    "value": "0x1bd2a40",
    "label": "lightningd/chaintopology.c:694:struct chain_topology",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "lightningd/chaintopology.c:694 (new_topology)",
      "lightningd/lightningd.c:93 (new_lightningd)",
      "lightningd/lightningd.c:252 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1bd2fe0",
    "label": "lightningd/invoice.c:69:struct invoices",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "lightningd/invoice.c:69 (invoices_init)",
      "lightningd/lightningd.c:96 (new_lightningd)",
      "lightningd/lightningd.c:252 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1d1b5a0",
    "label": "struct io_conn",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "ccan/ccan/io/io.c:94 (io_new_conn_)",
      "lightningd/subd.c:642 (new_subd)",
      "lightningd/subd.c:661 (new_global_subd)",
      "lightningd/gossip_control.c:125 (gossip_init)",
      "lightningd/lightningd.c:302 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1bf8d90",
    "label": "lightningd/txfilter.c:15:struct txfilter",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "lightningd/txfilter.c:15 (txfilter_new)",
      "lightningd/lightningd.c:282 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1c14cc0",
    "label": "struct pollfd[]",
    "parents": []
  },
  {
    "value": "0x1bd2830",
    "label": "wallet/wallet.c:18:struct wallet",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "wallet/wallet.c:18 (wallet_new)",
      "lightningd/lightningd.c:281 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1bd3920",
    "label": "char[]",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "ccan/ccan/tal/tal.c:496 (tal_alloc_arr_)",
      "ccan/ccan/tal/path/path.c:214 (path_canon)",
      "lightningd/lightningd.c:154 (find_my_path)",
      "lightningd/lightningd.c:260 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1c0f5e0",
    "label": "lightningd/options.c:571:u8[]",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "ccan/ccan/tal/tal.c:496 (tal_alloc_arr_)",
      "ccan/ccan/tal/tal.c:851 (tal_dup_)",
      "lightningd/options.c:571 (setup_color_and_alias)",
      "lightningd/lightningd.c:288 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1bd43c0",
    "label": "lightningd/lightningd.c:90:struct wireaddr[]",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "ccan/ccan/tal/tal.c:496 (tal_alloc_arr_)",
      "lightningd/lightningd.c:90 (new_lightningd)",
      "lightningd/lightningd.c:252 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1d5c780",
    "label": "lightningd/jsonrpc.c:624:struct json_connection",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "lightningd/jsonrpc.c:624 (jcon_connected)",
      "ccan/ccan/io/io.c:59 (next_plan)",
      "ccan/ccan/io/io.c:116 (io_new_conn_)",
      "ccan/ccan/io/poll.c:214 (accept_conn)",
      "ccan/ccan/io/poll.c:296 (io_loop)",
      "lightningd/lightningd.c:346 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "struct io_conn"
    ]
  },
  {
    "value": "0x1bda260",
    "label": "lightningd/options.c:580:u8[]",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "ccan/ccan/tal/tal.c:496 (tal_alloc_arr_)",
      "lightningd/options.c:580 (setup_color_and_alias)",
      "lightningd/lightningd.c:288 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  },
  {
    "value": "0x1d528c0",
    "label": "lightningd/jsonrpc.c:493:struct command",
    "backtrace": [
      "ccan/ccan/tal/tal.c:467 (tal_alloc_)",
      "lightningd/jsonrpc.c:493 (parse_request)",
      "lightningd/jsonrpc.c:595 (read_json)",
      "ccan/ccan/io/io.c:59 (next_plan)",
      "ccan/ccan/io/io.c:397 (io_ready)",
      "ccan/ccan/io/poll.c:305 (io_loop)",
      "lightningd/lightningd.c:346 (main)",
      "(null):0 ((null))",
      "../sysdeps/x86_64/start.S:120 ((null))",
      "(null):0 ((null))"
    ],
    "parents": [
      "lightningd/lightningd.c:70:struct lightningd"
    ]
  }
]
```
```
----------------------------------------------------------------------
Ran 1 test in 8.868s

FAILED (errors=1)
make[1]: *** [Makefile:182: pytest] Error 1
make[1]: Leaving directory '/home/jb55/dev/github/ElementsProject/lightning'
make: *** [Makefile:178: check] Error 2
```

**Comment by jb55** [comment]
hmmm might have been old object code lingering, looks like it went away after a make clean...

**Comment by jb55** [comment]
cool leak reports though
