### ISSUE TITLE
Plugins not working due to pyln.proto ShortChannelId import bug in gossmap.py

### ISSUE THREAD

**Issue by robotparty** [ElementsProject/lightning#4848]
### Issue and Steps to Reproduce
Error below is produced by all plugins. 

Add any plugin to this setup:
lightningd version: v0.10.1-193-gbb307fa
pyln-client: 0.10.1
pyln-proto: 0.10.1

I fixed it on my own install by changing line 5 in `/usr/local/lib/python3.8/dist-packages/pyln/client/gossmap.py` to read: 
`from pyln.proto.primitives import ShortChannelId, PublicKey`

Error message: 
```
Traceback (most recent call last):
  File "/home/lightningd/.lightning/plugins/rebalance/rebalance.py", line 2, in <module>
    from pyln.client import Plugin, Millisatoshi, RpcError
  File "/usr/local/lib/python3.8/dist-packages/pyln/client/__init__.py", line 3, in <module>
    from .gossmap import Gossmap, GossmapNode, GossmapChannel, GossmapNodeId
  File "/usr/local/lib/python3.8/dist-packages/pyln/client/gossmap.py", line 5, in <module>
    from pyln.proto import ShortChannelId, PublicKey
ImportError: cannot import name 'ShortChannelId' from 'pyln.proto' (/home/lightningd/.local/lib/python3.8/site-packages/pyln/proto/__init__.py)
```

### `getinfo` output
```
$ lc getinfo
{
   "id": "02daf5b7181aaf6eb4533b4b050944e949fc5f274c564341f14ef5748ed090fcd3",
   "alias": "satsori-earth",
   "color": "dc42f4",
   "num_peers": 6,
   "num_pending_channels": 0,
   "num_active_channels": 6,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "w7tgyghtsbwcoodnqqwooubboptl7uvh3f32jmbyzk344kgnxlmnjsid.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "10.88.88.68",
         "port": 9735
      }
   ],
   "version": "v0.10.1-193-gbb307fa",
   "blockheight": 703998,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/lightningd/.lightning/bitcoin"
}
```

**Comment by cdecker** [comment]
Seems like there is a missing `requirements.txt` entry in `pyln-client` to `pyln-proto` should be fixed in the next release.
