### ISSUE TITLE
Cannot compile v0.10.2 on Ubuntu 18.04.2 

### ISSUE THREAD

**Issue by got3nks** [ElementsProject/lightning#4903]
Running `git pull && ./configure && make`

```
mrkd doc/lightning-cli.1.md
/bin/sh: 1: mrkd: not found
doc/Makefile:107: recipe for target 'doc/lightning-cli.1' failed
make: *** [doc/lightning-cli.1] Error 127
```

**Comment by vincenzopalazzo** [comment]
Hi @got3nks,

The solution should be simple to install the python dependence with the following command `pip install mrkd`

**Comment by got3nks** [comment]
Build still fails

```
mrkd doc/lightning-cli.1.md
Traceback (most recent call last):
  File "/usr/local/bin/mrkd", line 7, in <module>
    from mrkd import main
  File "/home/bitcoincore/.local/lib/python2.7/site-packages/mrkd/__init__.py", line 42
    return f'{self.double_emphasis(text)}({section})'
                                                    ^
SyntaxError: invalid syntax
doc/Makefile:107: recipe for target 'doc/lightning-cli.1' failed
make: *** [doc/lightning-cli.1] Error 1
```

**Comment by got3nks** [comment]
Running `pip uninstall mrkd` and ` pip3 install mrkd` as root solved the issue.
