### ISSUE TITLE
Debian build error : AttributeError: module 'mistune' has no attribute 'InlineLexer'

### ISSUE THREAD

**Issue by tristram21** [ElementsProject/lightning#4973]
### I followed the instructions for compiling and installing from source for Ubuntu but on Debian 11 (bullseye).
**make** command exited with ` AttributeError: module 'mistune' has no attribute 'InlineLexer' `

I did : 
```
sudo apt-get update
sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev \
  python3 python3-mako python3-pip net-tools zlib1g-dev libsodium-dev \
  gettext
pip3 install --user mrkd

git clone https://github.com/ElementsProject/lightning.git
cd lightning

./configure

make
```
And It ouput : 
```
...

mrkd doc/lightning-cli.1.md
Traceback (most recent call last):
  File "/home/user/.local/bin/mrkd", line 5, in <module>
    from mrkd import main
  File "/home/user/.local/lib/python3.9/site-packages/mrkd/__init__.py", line 23, in <module>
    class ReferenceLexer(mistune.InlineLexer):
AttributeError: module 'mistune' has no attribute 'InlineLexer'
make: *** [doc/Makefile:115: doc/lightning-cli.1] Error 1

```

**Comment by vincenzopalazzo** [comment]
Hi, 

We fixed this error in https://github.com/ElementsProject/lightning/pull/4965 and the solution is to run the following command

`pip3 install --user mrkd mistune==0.8.4`

**Comment by tristram21** [comment]
Hi, thank you

after doing : 
```
pip3 install --user mrkd mistune==0.8.4

./configure

make
```

I have another error :
```
Traceback (most recent call last):
  File "/home/sam/lightning/tools/fromschema.py", line 280, in <module>
    main(parsed_args.schemafile, parsed_args.markdownfile)
  File "/home/sam/lightning/tools/fromschema.py", line 269, in main
    schema = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
make: *** [doc/Makefile:110: doc/lightning-addgossip.7.md] Error 1
```

**Comment by vincenzopalazzo** [comment]
Do your local version of lightning is corrupt? it looks like that there is some None value, somewhere, but I'm not able to catch why.

**Comment by tristram21** [comment]
Indeed it was corrupt, I cloned it again and followed the steps with the right mistune version and it worked! Sorry for this issue

**Comment by vincenzopalazzo** [comment]
>Indeed it was corrupt, I cloned it again and followed the steps with the right mistune version and it worked! Sorry for this issue

Happy that now your local version it is up and running 😄
