### ISSUE TITLE
CLN rust dependency won't build on ppc64le

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#5691]
Rocky Linux 9's rustc and cargo versions:
```
$ rustc --version
rustc 1.58.1 (Red Hat 1.58.1-1.el9)
```
```
$ cargo --version
cargo 1.58.0
```
I've recently been hitting this error building CLN master: 
```
genidx doc/index.rst
(cd plugins; cargo build --quiet --examples)
error: failed to parse manifest at `/home/user/builds/lightning/Cargo.toml`

Caused by:
  feature `strip` is required

  The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.58.0).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option for more information about the status of this feature.
make: *** [plugins/Makefile:210: target/debug/examples/cln-plugin-startup] Error 101
```

**Comment by vincenzopalazzo** [comment]
yeah, this is bad because we do not have the control over distribution version, what about installing rust from the official install script? 
https://www.rust-lang.org/tools/install

**Comment by whitslack** [comment]
My Gentoo ebuild for Core Lightning [deletes](https://gitlab.com/bitcoin/gentoo/-/blob/e626970e9ce4da50165ba58908eca0af9263c295/net-p2p/core-lightning/core-lightning-0.12.1.ebuild#L319-320) the `strip = "debuginfo"` line from `Cargo.toml` because stripping binaries for installation is the responsibility of the package manager, not of the build system, and stripping can be suppressed through Portage's `nostrip` feature flag, which doesn't work if the build system has already done it. Presumably if you delete that line as well, then your antique version of Cargo won't complain about it.

**Comment by grubles** [comment]
Commenting out the `strip = "debuginfo"` helps the build progress some, but then errors again. Looks like I'll have to reinstall rust using `rustup` in order to get a more recent version. 


```
(cd plugins; cargo build --quiet --examples)
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/user/builds/lightning/target/debug/build/ring-4dd82f7f52552798/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: build failed
make: *** [plugins/Makefile:210: target/debug/examples/cln-plugin-startup] Error 101
rm external/ppc64le-redhat-linux/libwally-core-build/src/secp256k1/libsecp256k1.la
```

**Comment by cdecker** [comment]
We could use `HAVE_CARGO` configure value reflect whether we have a `rustc` that is recent enough.

**Comment by vincenzopalazzo** [comment]
I think it is not a version problem but ring does not support some platform https://github.com/briansmith/ring/issues/562 and the error is a little bit cryptic because it is caused by this unwrap.

I think the only solution is disabling rust?

**Comment by grubles** [comment]
I was starting to suspect that was the case since I'm running on POWER9 rather than ARM or x86. :-/

**Comment by cdecker** [comment]
Ok, then we might get away by setting `RUST=0` in `config.vars`, that'll tell `make` to skip Rust components. Sadly that means that the `cln-grpc` will also not be compiled.

**Comment by grubles** [comment]
The `--disable-rust` configure flag seems to work for this.

**Comment by whitslack** [comment]
> The `--disable-rust` configure flag seems to work for this.

That's how we disable building+installing the Rust components on Gentoo when the user configures `USE="-rust"` despite having Rust installed. Works perfectly.

**Comment by cdecker** [comment]
Yeah, sorry about that, hopefully `ring` adds support to ppc, alternatively we could fall back on `openssl` rather than `rustls` (which then pulls in `ring` as a transitive dependency). Though not quite sure how to realize that type of config changes from the `./configure` script to the `Cargo.toml` in `plugins/grpc-plugin`, but we'll find a way.

**Comment by grubles** [comment]
It looks like `ring` is making progress towards a C fallback for all little endian archs actually. https://github.com/briansmith/ring/issues/1455

**Comment by grubles** [comment]
```
cargo build --quiet --example cln-plugin-startup
cargo build --quiet --example cln-plugin-reentrant
cargo build --quiet --bin cln-grpc
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/user/builds/lightning/target/debug/build/ring-9115534fec60a59d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [cln-rpc/Makefile:18: target/debug/examples/cln-plugin-reentrant] Error 101
make: *** Waiting for unfinished jobs....
```
Do we need to use the older ring 0.16.20 still? The latest version can build on ppc64le now.

**Comment by whitslack** [comment]
The hell arising from the contemporary obsession with version pinning and static linking. 🙄

**Comment by rustyrussell** [comment]
AI cleanup of old issues.  If wrong, please open a new issue.


Triage decision summary:
Issue reports Rust build failure on ppc64le due to unstable `strip` feature requiring Cargo 1.59+. Created Nov 2022, last updated May 2025. Likely resolved by Rust/Cargo version upgrades or removal of the strip feature requirement.
