### ISSUE TITLE
Upgrading to v22.11 broke pylightning

### ISSUE THREAD

**Issue by got3nks** [ElementsProject/lightning#5778]
After upgrading to version 22.11 our middleware based on **pylightning (v0.0.7.3)** stopped working.

```
dic 05 12:32:37 root python3[30925]: ERROR:aiohttp.server:Error handling request
dic 05 12:32:37 root python3[30925]: Traceback (most recent call last):
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
dic 05 12:32:37 root python3[30925]:     resp = await task
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
dic 05 12:32:37 root python3[30925]:     resp = await handler(request)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
dic 05 12:32:37 root python3[30925]:     return await handler(request)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/aiohttp_basicauth/__init__.py", line 65, in __call__
dic 05 12:32:37 root python3[30925]:     return await self.check_auth(request, handler)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/aiohttp_basicauth/__init__.py", line 50, in check_auth
dic 05 12:32:37 root python3[30925]:     return await handler(request)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/lightning-rest/lightning_rest/server.py", line 421, in wait_any_invoice
dic 05 12:32:37 root python3[30925]:     result = await loop.run_in_executor(None, caller)
dic 05 12:32:37 root python3[30925]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
dic 05 12:32:37 root python3[30925]:     result = self.fn(*self.args, **self.kwargs)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/lightning-rest/lightning_rest/server.py", line 420, in <lambda>
dic 05 12:32:37 root python3[30925]:     caller = lambda: wait_paid_invoice(request=request, lastpay_index=lastpay_index)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/lightning-rest/lightning_rest/server.py", line 412, in wait_paid_invoice
dic 05 12:32:37 root python3[30925]:     return request.app['rpc'].waitanyinvoice(lastpay_index)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/lightning/lightning.py", line 193, in waitanyinvoice
dic 05 12:32:37 root python3[30925]:     return self.call("waitanyinvoice", payload)
dic 05 12:32:37 root python3[30925]:   File "/home/bitcoincore/.local/lib/python3.6/site-packages/lightning/lightning.py", line 70, in call
dic 05 12:32:37 root python3[30925]:     payload
dic 05 12:32:37 root python3[30925]: ValueError: RPC call failed: {'code': -32600, 'message': 'jsonrpc: "2.0" must be specified in the request'}, method: waitanyinvoice, payload: {'lastpay_index': '727'}
dic 05 12:32:40 root python3[30925]: ERROR:aiohttp.server:Error handling request
```

Any suggestion on how to quickly fix this issue?

To replicate the error I created a simple _test.py_ script:

```
from lightning import LightningRpc

rpc = LightningRpc('/path/to/.lightning/bitcoin/lightning-rpc')
print(rpc.getinfo())
```

Which will produce the same error.

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(rpc.getinfo())
  File "/usr/local/lib/python3.6/dist-packages/lightning/lightning.py", line 526, in getinfo
    return self.call("getinfo")
  File "/usr/local/lib/python3.6/dist-packages/lightning/lightning.py", line 229, in call
    raise RpcError(method, payload, resp['error'])
lightning.lightning.RpcError: RPC call failed: method: getinfo, payload: {}, error: {'code': -32600, 'message': 'jsonrpc: "2.0" must be specified in the request'}
```

**Comment by devastgh** [comment]
> It worked, thanks!

Also, please replace pylightning. that version is very old and i think it has been renamed to pyln-client.
