### ISSUE TITLE
`pb::test::test_listpeers` and `test::test_listpeers` unit tests fail: "missing field `local_funds_msat`"

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#5899]
The Rust unit tests are failing at f1373fd98ca0f2907d2f25434da344efb58a8e08. I have not bisected to find the exact commit that introduced the failure, but I can if that would be helpful.

```
running 4 tests
test pb::test::test_listpeers ... FAILED
test test::test_getinfo ... ok
test test::test_listpeers ... FAILED
test test::test_keysend ... ok

failures:

---- pb::test::test_listpeers stdout ----
thread 'pb::test::test_listpeers' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `local_funds_msat`", line: 0, column: 0)', cln-grpc/src/pb.rs:369:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::test_listpeers stdout ----
thread 'test::test_listpeers' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `local_funds_msat`", line: 0, column: 0)', cln-grpc/src/test.rs:217:74


failures:
    pb::test::test_listpeers
    test::test_listpeers

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by vincenzopalazzo** [comment]
this should be fixed by https://github.com/ElementsProject/lightning/pull/5895 I merged it because it is just some housekeeping for listpeers splitting PR
