### ISSUE TITLE
GRPC Fundchannel: thread 'main' panicked

### ISSUE THREAD

**Issue by kiwiidb** [ElementsProject/lightning#5926]
### Issue and Steps to Reproduce
I am currently doing a re-run of @joostjager 's lightning-benchmark. My fork where I implemented a CLN GRPC client is [here](https://github.com/getAlby/lightning-benchmark/tree/feature/cln-grpc). I've spun up 2 CLN nodes and a bitcoind node on regtest inside k8s cluster. The CLN version is v22.11. When I try to fund the channels over GRPC [code](https://github.com/getAlby/lightning-benchmark/blob/feature/cln-grpc/loadtest/cln_grpc.go#L112), the call hangs indefinetely. CLN logs indicate the following:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPublicKey', cln-grpc/src/convert.rs:1489:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPublicKey', cln-grpc/src/convert.rs:1489:46
```
The `loadtester` logs:
```
Starting setup...
2023-01-26T14:51:38.430Z	INFO	Attempting to connect to bitcoind
2023-01-26T14:51:38.461Z	INFO	Connected to bitcoind
2023-01-26T14:51:38.461Z	INFO	Using dummy address	{"address": "bcrt1qlppjvkglr9hrznfnx94n4np53axcekzer9dkmv"}
2023-01-26T14:51:38.461Z	INFO	Activate segwit
2023-01-26T14:52:03.826Z	INFO	Creating bitcoind wallet
2023-01-26T14:52:06.867Z	INFO	Fund sender
2023-01-26T14:52:06.915Z	INFO	Generated funding address	{"address": "bcrt1qvhmez5tm3vjlvp452xl42y8sc8pjlv6x903n3s"}
2023-01-26T14:52:13.317Z	INFO	Mature coin
2023-01-26T14:52:20.630Z	INFO	Wait for coin to appear in wallet
2023-01-26T14:52:20.708Z	INFO	Receiver info	{"pubkey": "02b0638b0e6888525e1508c9ea61218e043483850f34d782484ef05bb4527dce93"}
2023-01-26T14:52:20.708Z	INFO	Connecting peers
2023-01-26T14:52:20.749Z	INFO	Open channels	{"channel_count": 10, "capacity_sat": 10000000}
```
CLN itself also seems to hang, `lightning-cli getinfo` doesn't work anymore. When I mine some blocks on bitcoind, CLN crashes with 
```
Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket.Lost connection to the RPC socket
```
and restarts. 

### `getinfo` output
```
{
   "id": "03de2b7b91b39f3009a685244920ae9421cf4b4f195011d6dc5592981119f2b4bc",
   "alias": "GREENPLOW-v22.11",
   "color": "03de2b",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v22.11",
   "blockheight": 6245,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/root/.lightning/regtest",
   "our_features": {
      "init": "08a0800a0269a2",
      "node": "88a0800a0269a2",
      "channel": "",
      "invoice": "02000002024100"
   }
}
```

**Comment by cdecker** [comment]
That appears to be an issue in the conversion code. This can happen if the schema from which we generate the bindings isn't quite correct, and we therefore make a wrong assumption in the conversion.

The `convert.rs` script is there to convert from grpc request message to in-memory Rust structs and the other direction from in-memory Rust structs to grpc response message. Either of these directions could be the ones that are hit here. Checking with the release version of cln-grpc 0.1.2 we see this code:

```
impl From<pb::FundchannelRequest> for requests::FundchannelRequest {
    fn from(c: pb::FundchannelRequest) -> Self {
        Self {
            id: PublicKey::from_slice(&c.id).unwrap(), // Rule #1 for type pubkey
            amount: c.amount.unwrap().into(), // Rule #1 for type msat_or_all
            feerate: c.feerate.map(|a| a.into()), // Rule #1 for type feerate?
            announce: c.announce, // Rule #1 for type boolean?
            minconf: c.minconf, // Rule #1 for type u32?
            push_msat: c.push_msat.map(|a| a.into()), // Rule #1 for type msat?
            close_to: c.close_to, // Rule #1 for type string?
            request_amt: c.request_amt.map(|a| a.into()), // Rule #1 for type msat?
            compact_lease: c.compact_lease, // Rule #1 for type string?
            utxos: Some(c.utxos.into_iter().map(|s| s.into()).collect()), // Rule #4
            mindepth: c.mindepth, // Rule #1 for type u32?
            reserve: c.reserve.map(|a| a.into()), // Rule #1 for type msat?
        }
    }
}
```
Where the `id` line is at 1489, which is where the error triggers. This is the grpc -> Rust struct direction, and would suggest that the mandatory (non-optional) field `id` is either not a hex string, doesn't encode 33 bytes of data, or doesn't begin with a `0x02` or `0x03` byte.

Haven't looked at your client code yet, but is it possible that the call simply isn't correct?

Either way, we should likely get less upset about these validation errors. Migrating to `TryFrom` instead of `From` might be the ticket here.
