### ISSUE TITLE
Getting issue in installation!

### ISSUE THREAD

**Issue by anmode** [ElementsProject/lightning#6157]
### Issue and Steps to Reproduce
On running `poetry run make `
and i have tried to install pyenv but then too!
```
anmode@Anmols-MacBook-Air lightning % poetry run make        
CC: cc -I/usr/local/opt/sqlite/include -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/arm64-apple-darwin22.3.0/libbacktrace-build -I . -I/opt/homebrew/include -I/opt/homebrew/opt/sqlite/include     -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DCOMPAT_V072=1 -DCOMPAT_V073=1 -DCOMPAT_V080=1 -DCOMPAT_V081=1 -DCOMPAT_V082=1 -DCOMPAT_V090=1 -DCOMPAT_V0100=1 -DCOMPAT_V0121=1 -DBUILD_ELEMENTS=1  -c -o
LD: cc -L/usr/local/opt/sqlite/lib   -Og  config.vars  -Lexternal/arm64-apple-darwin22.3.0 -lwallycore -lsecp256k1 -ljsmn -lbacktrace -L/opt/homebrew/include -lm -lgmp -L/opt/homebrew/opt/sqlite/lib -lsqlite3 -lz  -lsodium -o
wiregen hsmd/hsmd_wiregen.h
Traceback (most recent call last):
  File "/Users/anmode/lightning/tools/generate-wire.py", line 27, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
make: *** [hsmd/hsmd_wiregen.h] Error 1
```

**Comment by vincenzopalazzo** [comment]
Try this!
```
poetry shell
poetry install
make
sudo make install
```

**Comment by anmode** [comment]
Getting error here: 
```
anmode@Anmols-MacBook-Air lightning % poetry shell
Spawning shell within /Users/anmode/Library/Caches/pypoetry/virtualenvs/cln-meta-project-2YNMSMpj-py3.11
anmode@Anmols-MacBook-Air lightning % emulate bash -c '. /Users/anmode/Library/Caches/pypoetry/virtualenvs/cln-meta-project-2YNMSMpj-py3.11/bin/activate'
(cln-meta-project-py3.11) anmode@Anmols-MacBook-Air lightning % poetry install
Installing dependencies from lock file

Package operations: 13 installs, 2 updates, 0 removals

  • Updating pyln-proto (22.11rc1 /Users/anmode/lightning/contrib/pyln-proto -> 0.11.1 /Users/anmode/lightning/contrib/pyln-proto)
  • Installing grpcio (1.47.0): Preparing...
  • Installing psycopg2-binary (2.9.3): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /private/var/folders/l2/2157bwts2bxc4ttrrdfgwrj00000gn/T/tmp02ae601z/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running egg_info
  writing psycopg2_binary.egg-info/PKG-INFO
  writing dependency_links to psycopg2_binary.egg-info/dependency_links.txt
  writing top-level names to psycopg2_binary.egg-info/top_level.txt
  
  Error: pg_config executable not found.
  
  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:
  
      python setup.py build_ext --pg-config /path/to/pg_config build ...
  
  or with the pg_config option in 'setup.cfg'.
  
  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
  
  

  at /opt/homebrew/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2-binary (2.9.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psycopg2-binary (==2.9.3)"'.

```

Afterwards on running make same error!
```
(cln-meta-project-py3.11) anmode@Anmols-MacBook-Air lightning % make
CC: cc -I/usr/local/opt/sqlite/include -DBINTOPKGLIBEXECDIR="../libexec/c-lightning" -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -Werror -std=gnu11 -g -fstack-protector-strong -Og -I ccan -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbacktrace/ -I external/gheap/ -I external/arm64-apple-darwin22.3.0/libbacktrace-build -I . -I/opt/homebrew/include -I/opt/homebrew/opt/sqlite/include     -DSHACHAIN_BITS=48 -DJSMN_PARENT_LINKS  -DCOMPAT_V052=1 -DCOMPAT_V060=1 -DCOMPAT_V061=1 -DCOMPAT_V062=1 -DCOMPAT_V070=1 -DCOMPAT_V072=1 -DCOMPAT_V073=1 -DCOMPAT_V080=1 -DCOMPAT_V081=1 -DCOMPAT_V082=1 -DCOMPAT_V090=1 -DCOMPAT_V0100=1 -DCOMPAT_V0121=1 -DBUILD_ELEMENTS=1  -c -o
LD: cc -L/usr/local/opt/sqlite/lib   -Og  config.vars  -Lexternal/arm64-apple-darwin22.3.0 -lwallycore -lsecp256k1 -ljsmn -lbacktrace -L/opt/homebrew/include -lm -lgmp -L/opt/homebrew/opt/sqlite/lib -lsqlite3 -lz  -lsodium -o
wiregen hsmd/hsmd_wiregen.h
Traceback (most recent call last):
  File "/Users/anmode/lightning/tools/generate-wire.py", line 27, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
make: *** [hsmd/hsmd_wiregen.h] Error 1

```

**Comment by anmode** [comment]
Okay this solves! I have to install mako. Thankss
```
pip install mako
```

**Comment by vincenzopalazzo** [comment]
Yeah, PR to update the osx docs are welcome btw :)
