### ISSUE TITLE
Error on grpcio during `poetry install` on macOS

### ISSUE THREAD

**Issue by sugarjig** [ElementsProject/lightning#6293]
### Issue and Steps to Reproduce

I'm on macOS 13.4. I'm trying to build from the 23.05 tag.

After installing the dependencies using Homebrew, I try to run `poetry install` but get the following on grpcio:

```
• Installing grpcio (1.47.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
```

followed by a lot of output from clang commands, then:

<details>
<summary>a stack trace</summary>

```
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpfduakv9h/a.c -o None/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpfduakv9h/a.o
  Traceback (most recent call last):
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/commands.py", line 280, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
                ^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
      multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 367, in map
      return self._map_async(func, iterable, mapstar, chunksize).get()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
      raise self._value
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
                      ^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
      return list(map(*args))
             ^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/commands.py", line 263, in new_compile
      return old_compile(obj, src, ext, cc_args, extra_postargs,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/poetry/1.5.1/libexec/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/Cellar/poetry/1.5.1/libexec/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/poetry/1.5.1/libexec/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 541, in <module>
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/commands.py", line 284, in build_extensions
      raise CommandError(
  commands.CommandError: Failed `build_ext` step:
  Traceback (most recent call last):
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
      spawn(cmd, dry_run=self.dry_run, **kwargs)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/commands.py", line 280, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
                ^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
      multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 367, in map
      return self._map_async(func, iterable, mapstar, chunksize).get()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
      raise self._value
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
                      ^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
      return list(map(*args))
             ^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmpxtm_wc5a/grpcio-1.47.0/src/python/grpcio/commands.py", line 263, in new_compile
      return old_compile(obj, src, ext, cc_args, extra_postargs,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/tm/3p8vnm152l3ck8zk_b42ph2m0000gp/T/tmp59z4xjgl/.venv/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
```
</details>

and then:

```
Note: This error originates from the build backend, and is likely not a problem with poetry but with grpcio (1.47.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "grpcio (==1.47.0)"'.
```

I don't see anything obviously useful in the stack trace.

### `getinfo` output

N/A?

**Comment by sugarjig** [comment]
The problem turned out to be a simple one. Poetry was picking up Python 3.11 from my system. Telling it to use 3.8 fixed the problem.

**Comment by SatoriHoshiAiko** [comment]
I had better success doing this with 3.9.13 - I had to manually use the pyenv install poetry under /Users/username/.pyenv/versions/3.9.13/bin/poetry install (and run make) since I had poetry already installed in /opt/homebrew/bin/poetry.

For some reason 3.8.10 still fails for gracious 1.47.0 , but 3.9.13 (my old preferred) did poetry run make fine. Maybe someone else can test building with 3.9.13 also I am on Ventura 13.4.1 - If there is repeated success it might be worth updating this in osx build docs. Not sure why but 3.8.10 failed for me, 3.9.13 ran perfect.
