### ISSUE TITLE
make install fails on v23.08

### ISSUE THREAD

**Issue by nolash** [ElementsProject/lightning#6660]
### Issue and Steps to Reproduce

make install fails on v23.08, using rust 1.65.0, debian buster

```
cargo build --quiet --bin cln-grpc
error: failed to run custom build command for `cln-grpc v0.1.3 (/home/lash/src/lightning/cln-grpc)`

Caused by:
  process didn't exit successfully: `/home/lash/src/lightning/target/debug/build/cln-grpc-73c7442a945f86d4/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto/node.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }', cln-grpc/build.rs:6:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [plugins/Makefile:249: target/debug/cln-grpc] Error 101
rm external/build-x86_64-linux-gnu/libwally-core-build/src/secp256k1/libsecp256k1.la

```

with backtrace ():

```
$ RUST_BACKTRACE=1 cargo build --quiet --bin cln-grpc
error: failed to run custom build command for `cln-grpc v0.1.3 (/home/lash/src/lightning/cln-grpc)`

Caused by:
  process didn't exit successfully: `/home/lash/src/lightning/target/debug/build/cln-grpc-73c7442a945f86d4/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto/node.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }', cln-grpc/build.rs:6:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1107:23
     4: build_script_build::main
               at ./build.rs:3:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtra
```

**Comment by vincenzopalazzo** [comment]
From ` "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" ` looks like that you have an old protoc version?

If you do not care about rust, you can run `sudo make install RUST=0` or just install the new version of protoc (?)

**Comment by nolash** [comment]
> or just install the new version of protoc

perhaps not too practical on the buster system. perhaps a `--configure`  param to choose custom protoc dir could work?

Anyway, for my part I don't need rust so all good (and also just now noticed the configure param for that, too), thanks.

**Comment by vincenzopalazzo** [comment]
>perhaps not too practical on the buster system. perhaps a --configure param to choose custom protoc dir could work?

I think the correct solution is install the new protoc from https://github.com/protocolbuffers/protobuf/releases

Usually people with complex project will give up to make package for ppa because looks like tricky in some case

**Comment by vincenzopalazzo** [comment]
Ok, I am closing this due to there being silence for a while. I am assuming that the new protoc solve the problem?

Otherwise feel free to reopen it and provide more details
