### ISSUE TITLE
riscv arch requires linking to libatomic?

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#7044]
From what I gather, there is a [bug in gcc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81358) that causes libatomic to not be automatically linked on some architectures. 

```
python3 -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-grpc-proto/pyln/grpc/ --grpc_python_out=contrib/pyln-grpc-proto/pyln/grpc/ --experimental_allow_proto3_optional                                                                
Traceback (most recent call last):                                                         
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main    
    return _run_code(code, main_globals, None,              
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code 
    exec(code, run_globals)                
  File "/home/user/.cache/pypoetry/virtualenvs/cln-meta-project-YocaCd4z-py3.10/lib/python3.10/site-packages/grpc_tools/protoc.py", line 20, in <module>
    from grpc_tools import _protoc_compiler                                                
ImportError: /home/user/.cache/pypoetry/virtualenvs/cln-meta-project-YocaCd4z-py3.10/lib/python3.10/site-packages/grpc_tools/_protoc_compiler.cpython-310-riscv64-linux-gnu.so: undefined symbol: __atomic_compare_exchange_1                                                     
make: *** [Makefile:388: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Error 1
```

Notice this machine does have libatomic:

```
$ find /usr/|grep libatomic.so
/usr/lib/riscv64-linux-gnu/libatomic.so.1
/usr/lib/riscv64-linux-gnu/libatomic.so.1.2.0
/usr/lib/gcc/riscv64-linux-gnu/11/libatomic.so
```

```
$ cc --version
cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

**Comment by cdecker** [comment]
This is an upstream issue with grpcio, please refer to their docs to see what the solution should be.

**Comment by grubles** [comment]
I'll file a ticket upstream. Seems similar to this but for riscv instead of arm. https://github.com/grpc/grpc/issues/20400

**Comment by grubles** [comment]
```
$ pip install grpcio
Defaulting to user installation because normal site-packages is not writeable
Collecting grpcio
  Downloading grpcio-1.60.1.tar.gz (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... done
  Created wheel for grpcio: filename=grpcio-1.60.1-cp310-cp310-linux_riscv64.whl size=83411996 sha256=fb1c31d8cafbd0078b8d91268ab02484ae76502ede062fd62d3c7dad01fabe4b
  Stored in directory: /home/user/.cache/pip/wheels/bd/db/e2/749f91fbf9a0ed07031f8240d9b500191f814a0d846c6a43d6
Successfully built grpcio
Installing collected packages: grpcio
Successfully installed grpcio-1.60.1
```
1.60.1 builds fine on riscv. Do we need specifically need 1.59.2?
