### ISSUE TITLE
Failed to open pipe in plugin clnrest

### ISSUE THREAD

**Issue by nolash** [ElementsProject/lightning#7862]
### Issue and Steps to Reproduce

Version 23.08 when running with clnrest:

```
2024-11-23T19:27:45.116Z DEBUG   plugin-manager: started(3952) /home/lash/src/lightning/build/libexec/c-lightning/plugins/commando
2024-11-23T19:27:45.121Z DEBUG   plugin-manager: started(3953) /home/lash/src/lightning/build/libexec/c-lightning/plugins/fetchinvoice
2024-11-23T19:27:45.127Z DEBUG   plugin-manager: started(3954) /home/lash/src/lightning/build/libexec/c-lightning/plugins/funder
2024-11-23T19:27:45.131Z DEBUG   plugin-manager: started(3955) /home/lash/src/lightning/build/libexec/c-lightning/plugins/topology
2024-11-23T19:27:45.137Z DEBUG   plugin-manager: started(3956) /home/lash/src/lightning/build/libexec/c-lightning/plugins/keysend
2024-11-23T19:27:45.142Z DEBUG   plugin-manager: started(3957) /home/lash/src/lightning/build/libexec/c-lightning/plugins/offers
2024-11-23T19:27:45.148Z DEBUG   plugin-manager: started(3958) /home/lash/src/lightning/build/libexec/c-lightning/plugins/pay
2024-11-23T19:27:45.153Z DEBUG   plugin-manager: started(3959) /home/lash/src/lightning/build/libexec/c-lightning/plugins/txprepare
2024-11-23T19:27:45.158Z DEBUG   plugin-manager: started(3960) /home/lash/src/lightning/build/libexec/c-lightning/plugins/cln-renepay
2024-11-23T19:27:45.163Z DEBUG   plugin-manager: started(3961) /home/lash/src/lightning/build/libexec/c-lightning/plugins/spenderp
2024-11-23T19:27:45.170Z DEBUG   plugin-manager: started(3962) /home/lash/src/lightning/build/libexec/c-lightning/plugins/sql
2024-11-23T19:27:45.174Z DEBUG   plugin-manager: started(3963) /home/lash/src/lightning/build/libexec/c-lightning/plugins/bookkeeper
2024-11-23T19:27:45.180Z DEBUG   plugin-manager: started(3964) /home/lash/src/lightning/build/libexec/c-lightning/plugins/clnrest/clnrest.py
error starting plugin '/home/lash/src/lightning/build/libexec/c-lightning/plugins/clnrest': opening pipe: Permission denied
(.venv) lash@maestoso:~$ Traceback (most recent call last):
  File "/home/lash/src/lightning/build/libexec/c-lightning/plugins/clnrest/clnrest.py", line 23, in <module>
    getmanifest = json.loads(sys.stdin.readline())
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

python environment:

```
$ pip freeze
aniso8601==9.0.1
asn1crypto==1.5.1
attrs==22.1.0
backports.cached-property==1.0.2
base58==2.1.1
bidict==0.22.1
bitstring==3.1.9
CacheControl==0.12.12
cachy==0.3.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
cleo==1.0.0a5
click==8.1.7
coincurve==18.0.0
crashtest==0.3.1
cryptography==41.0.7
distlib==0.3.6
dulwich==0.20.46
filelock==3.8.0
Flask==2.2.5
Flask-Cors==5.0.0
flask-restx==1.3.0
Flask-SocketIO==5.4.1
gevent==22.10.2
gevent-websocket==0.10.1
greenlet==3.1.1
gunicorn==23.0.0
h11==0.14.0
html5lib==1.1
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.10.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
jeepney==0.8.0
Jinja2==3.1.4
json5==0.9.16
jsonschema==4.16.0
keyring==23.9.3
Mako==1.2.3
MarkupSafe==2.1.1
more-itertools==9.0.0
msgpack==1.0.4
packaging==21.3
pexpect==4.8.0
pkg_resources==0.0.0
pkginfo==1.8.3
pkgutil_resolve_name==1.3.10
platformdirs==2.5.2
poetry==1.2.2
poetry-core==1.3.2
poetry-plugin-export==1.1.2
ptyprocess==0.7.0
pycparser==2.21
pylev==1.4.0
pyln-bolt7==1.0.246
pyln-client==23.5.2
pyln-proto==23.5.2
pyparsing==3.0.9
pyrsistent==0.18.1
PySocks==1.7.1
python-engineio==4.10.1
python-socketio==5.11.0
pytz==2024.2
requests==2.28.1
requests-toolbelt==0.9.1
SecretStorage==3.3.3
shellingham==1.5.0
simple-websocket==1.1.0
six==1.16.0
tomlkit==0.11.5
typing_extensions==4.4.0est interface
urllib3==1.26.12
virtualenv==20.16.5
webencodings==0.5.1
Werkzeug==2.2.3
wsproto==1.2.0
zipp==3.9.0
zope.event==5.0
zope.interface==6.4.post2
```

### `getinfo` output

... cant start node

**Comment by nolash** [comment]
Doesn't work with 3.7. Changed to 3.8. Now getting:

```
$ ./build/bin/lightning-cli -k plugin subcommand=start plugin=/home/lash/src/lightning/build/libexec/c-lightning/plugins/clnrest rest-port=3010
{
   "code": -3,
   "message": "/home/lash/src/lightning/build/libexec/c-lightning/plugins/clnrest: opening pipe: Permission denied"
}
```

**Comment by nolash** [comment]
same problem in 24.05

**Comment by rustyrussell** [comment]
Hmm, this strace doesn't show the failure, as it's in the Python code.  If you run `/home/lash/src/lightning/build/libexec/c-lightning/plugins/clnrest` manually, does it work?

**Comment by ddustin** [comment]
Running into the same issue while running tests locally on my Mac. I'm guessing this is a Mac issue.

Looks like a file permission issue.
```sh
% plugins/clnrest
zsh: permission denied: plugins/clnrest
```

**Comment by ddustin** [comment]
Ah I believe it's a pathing issue.

Adding the path to the log message:
```c
	p->pid = pipecmdarr(&stdinfd, &stdoutfd, &pipecmd_preserve, cmd);
	if (p->pid == -1)
		return tal_fmt(p, "opening pipe: %s; cmd[0]: %s",
			       strerror(errno), cmd[0]);
```

```
error starting plugin '/..trim../plugins/clnrest': opening pipe: Permission denied; cmd[0]: /..trim../plugins/clnrest
```

```
% /..trim../plugins/clnrest
zsh: permission denied: /..trim../plugins/clnrest
% /..trim../plugins/clnrest/clnrest
[program runs]
```

The permission denied is because it's trying to run the *folder* instead of the program.

**Comment by nolash** [comment]
Thanks, adding the additional `clnrest` part to the path worked. I was now able to run it, substituing the `rest-port` parameter with `clnrest-port`.

This is my current python setup:

```
cryptography==38.0.4
ghp-import==2.1.0
gunicorn==20.1.0
httplib2==0.20.4
idna==3.3
iniconfig==1.1.1
Jinja2==3.1.2
joblib==1.2.0
livereload==2.6.3
lunr==0.6.2
Markdown==3.4.1
MarkupSafe==2.1.2
mergedeep==1.3.4
mkdocs==1.4.2
more-itertools==8.10.0
nltk==3.8
numpy==1.24.2
packaging==23.0
pipx==1.1.0
pluggy==1.0.0+repack
psutil==5.9.4
py==1.11.0
pycurl==7.45.2
Pygments==2.14.0
pyinotify==0.9.6
pyOpenSSL==23.0.0
pyparsing==3.0.9
PySimpleSOAP==1.16.2
pytest==7.2.1
python-apt==2.6.0
python-dateutil==2.8.2
python-debian==0.1.49
python-debianbts==4.0.1
pytz==2022.7.1
PyYAML==6.0
pyyaml_env_tag==0.1
regex==2022.10.31
reportbug==12.0.0
requests==2.28.1
simplejson==3.18.3
six==1.16.0
speedtest-cli==2.1.3
stdeb==0.10.0
tornado==6.2
tqdm==4.64.1
urllib3==1.26.12
userpath==1.8.0
watchdog==2.2.1
```
